### ISSUE TITLE
3,000 samples or 4,000 samples?

### ISSUE THREAD

**Issue by xlchen0205** [yakir-yehuda/InterrogateLLM#1]
Hello, 

I am an enthusiast of your recent work and have been going through both your paper and the associated code on GitHub.

In your paper, it is stated that a sample size of 3,000 samples was used for the Movies and Books datasets. However, upon reviewing the code provided, I noticed that the sampling size appears to be set at 4,000. This discrepancy has raised a question for me regarding which sample size should be considered accurate or intended for replication of the study.

Thank you very much for your attention to this matter. I am looking forward to your response and any insights you can share.

**Comment by yakir-yehuda** [comment]
Hello,

The correct sample size used in the study is indeed 3,000 for both the Movies and Books datasets. The discrepancy you noticed, with the code showing a sample size of 4,000, is due to our method of running the experiments. We initially process 4,000 samples and save checkpoints at every 100 examples. However, due to resource constraints and the need to complete evaluations across all experiments at the time, we finalized our analyses at the 3,000-sample checkpoint. Therefore, the sample size of 3,000 is the accurate one for replication purposes, as used in all our reported results.

I hope this clarifies the discrepancy. Please feel free to reach out if you have any further questions or need additional details.

Thanks
